rtsp_url: rtsp://<username>:<passwort>@123.45.6.78/live1
interval_seconds: 60       # Time between snapshots
duration_minutes: 30       # Total run time
output_dir: "snapshots"    # Where to save images
timelapse:
  enabled: true
  fps: 24                  # Frames per second for the output video
  output_file: "timelapse.mp4"
